config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/home'

  get 'pages/about'

  resources :articles do
    resources :comments
  end

  resources :users
  

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user #, :foreign_key => 'user_name', :primary_key => 'user_name'
	has_many :comments
	validates :title, presence: true, length: { maximum: 50 }
	validates :post, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles
	validates :password, presence: true, length: {minimum: 8}
	validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    # @articles = Article.all
    @articles = Article.joins("LEFT JOIN `users` ON users.id = articles.user_id").group("articles.user_id").select("articles.*, users.email AS user_email")
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    # @article = Article.select("articles.*, users.email AS user_email").joins("LEFT JOIN `users` ON users.id = articles.user_id").where("articles.id", params[:id])
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    # @user = User.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @user = User.all

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :post, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		redirect_to article_path(@article)
	end
	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
	    respond_to do |format|
	      format.html { redirect_to article_path(@article), notice: 'Comment was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	end
	private # WARN: functions will be private starting this line
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :post %><br>
    <%= f.text_area :post %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "MyRoRBlog Articles") %>
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Article', new_article_path, class: "btn btn-primary btn-block", style: "color: #fff;" %><br />

<div class="panel panel-default">
  <!-- Default panel contents -->
  <% provide(:title, "MyRoRBlog Articles") %>
  <div class="panel-heading">
    Listing Articles
  </div>
  <!-- <div class="panel-body">
    <p>...</p>
  </div> -->

  <!-- Table -->
  <div class="table-responsive">
    <table class="table table-bordered table-condensed">
      
      <thead>
        <tr class="danger">
          <th class="text-center">#</th>
          <th>Title</th>
          <th>Post</th>
          <th>User</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td class="text-center"><%= article.id %></td>
            <td><%= article.title %></td>
            <td class="text-center"><%= article.post %></td>
            <td><%= article.user_email %></td>
            <td>
              <!-- <div></div> -->
              <%= link_to 'Show', article, class: "btn btn-default btn-block" %>
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-default btn-block" %>
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-block" %>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/articles/new.html.erb
<% provide(:title, "MyRoRBlog Articles") %>
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% provide(:title, "MyRoRBlog Articles") %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>

<h2>Comments</h2>
<% # we're on the loop! %>
<% @article.comments.each do |comment| %>
	<p>
		<strong>Commenter:</strong>
		<%= comment.commenter %>
	</p>
	<p>
		<strong>Comment:</strong>
		<%= comment.body %>
	</p>
	<p>
		<% # article_comment_path are set in routes as a article_comment. Mind these namings! %>
		<%= link_to 'Delete', article_comment_path(@article.id, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>
<% end %>

<h2>Add a comment</h2>

<% # this is a form %>
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		<%= f.label :commenter %><br />
		<%= f.text_field :commenter %><br />
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_field :body %><br />
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#"><%= yield(:title) %></a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
	        <!-- <li><a href="#">Link</a></li> -->
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Samples <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	          	<li><%= link_to 'Articles', articles_path %></li>
	          	<li role="separator" class="divider"></li>
	          	<li><%= link_to 'Static Pages - Home', pages_home_path %></li>
	          	<li><%= link_to 'Static Pages - About', pages_about_path %></li>
	            <!-- <li role="separator" class="divider"></li> -->
	          </ul>
	        </li>
	      </ul>
	      <!-- <form class="navbar-form navbar-left">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li role="separator" class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul> -->
	    </div><!-- /.navbar-collapse -->
	    
	  </div><!-- /.container-fluid -->
	</nav>
	<%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<% provide(:title, "MyRoRBlog About") %>
<div class="jumbotron">
	<h1>About Us</h1>
	<p>I love enemies</p>
	<p>
		<a href="mailto:johncyrillcorsanes@gmail.com">Mail Me!</a>
	</p>
</div>

app/views/pages/home.html.erb
<% provide(:title, "MyRoRBlog Home") %>
<div class="jumbotron">
	<h1>Home</h1>
	<p>Diz iz mah crib, mah hommie</p>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>